FROM golang:1.22.3 AS build
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY *.go ./

RUN CGO_ENABLED=0 GOOS=linux go build
# RUN CGO_ENABLED=0 GOOS=linux go build -o /svclookup

# Run the tests in the container
FROM build AS test-stage
RUN go test -v ./...

# Deploy the application binary into a lean image
FROM gcr.io/distroless/base-debian11 AS release-stage
WORKDIR /

COPY --from=build-stage /svclookup /svclookup

EXPOSE 8080
USER nonroot:nonroot

ENTRYPOINT ["/svclookup"]
